### ISSUE TITLE
KeyError with .DZT file

### ISSUE THREAD

**Issue by RF801** [iannesbitt/gpx2dzg#2]
Hi,
Not sure if I am using the tool wrong.   But I get a KeyError when I try to input a standard .DZT file.   Attaching files.   Thanks!

(base) C:\Users\argo7\Downloads>gpx2dzg -d FILE____032.DZT -g 20240327145022-32144-data.gpx
2024-03-28 17:48:23 - dzx file: FILE____032.DZT
2024-03-28 17:48:23 - gpx file: 20240327145022-32144-data.gpx
2024-03-28 17:48:23 - WARNING: no time zero specified for channel 0, defaulting to rh_zero value (0)
2024-03-28 17:48:23 - WARNING: no DZG file found for GPS input
2024-03-28 17:48:23 - WARNING: could not find DZX file to read metadata. Trying to read array for marks...
2024-03-28 17:48:23 - DZT marks read successfully. marks: 11
2024-03-28 17:48:23 -                             traces: [0, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000]
2024-03-28 17:48:23 - found a SIR-3000 DZT file. reading marks now.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\argo7\anaconda3\Scripts\gpx2dzg.exe\__main__.py", line 7, in <module>
  File "C:\Users\argo7\anaconda3\Lib\site-packages\gpx2dzg\gpx2dzg.py", line 124, in main
    convert(dzx=dzx, gpx=gpx, plot=plot, write=write, drops=drops)
  File "C:\Users\argo7\anaconda3\Lib\site-packages\gpx2dzg\gpx2dzg.py", line 44, in convert
    dzxmarks = io.readSIR3k(dzt=dzx)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\argo7\anaconda3\Lib\site-packages\gpx2dzg\io.py", line 99, in readSIR3k
    markrow = arr[1][1]
              ~~~~~~^^^
KeyError: 1
[Uploading FILE____032.zip…]()

**Comment by aritzurruela** [comment]
Same problem here. Any solution?

'runfile('E:/CAMPAÑAS GEOFÍSICA/2024/2024.6.1 (MALLORCA GPR MGMT)/gpr/GPX/gpx to.py', wdir='E:/CAMPAÑAS GEOFÍSICA/2024/2024.6.1 (MALLORCA GPR MGMT)/gpr/GPX')
2024-05-16 13:50:10 - dzx file: 001.DZT
2024-05-16 13:50:10 - gpx file: 001.gpx
2024-05-16 13:50:10 - WARNING: no time zero specified for channel 0, defaulting to rh_zero value (0)
2024-05-16 13:50:10 - WARNING: no DZG file found for GPS input
2024-05-16 13:50:10 - WARNING: could not find DZX file to read metadata. Trying to read array for marks...
2024-05-16 13:50:10 - DZT marks read successfully. marks: 17
2024-05-16 13:50:10 -                             traces: [120, 240, 360, 480, 600, 720, 840, 960, 1080, 1200, 1320, 1440, 1560, 1680, 1800, 1920, 2040]
2024-05-16 13:50:10 - found a SIR-3000 DZT file. reading marks now.
Traceback (most recent call last):

  File "C:\Users\Aritz\Anaconda3\envs\gpx2dzg\lib\site-packages\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "e:\campañas geofísica\2024\2024.6.1 (mallorca gpr mgmt)\gpr\gpx\gpx to.py", line 8, in <module>
    g2d.convert(dzx='001.DZT', gpx='001.gpx')

  File "C:\Users\Aritz\Anaconda3\envs\gpx2dzg\lib\site-packages\gpx2dzg\gpx2dzg.py", line 44, in convert
    dzxmarks = io.readSIR3k(dzt=dzx)

  File "C:\Users\Aritz\Anaconda3\envs\gpx2dzg\lib\site-packages\gpx2dzg\io.py", line 99, in readSIR3k
    markrow = arr[1][1]

KeyError: 1'

**Comment by aritzurruela** [comment]
Hi there! Anyone found a solution?

**Comment by DMSMO** [comment]
I ran into the same problem, used readgssi v0.0.15 and it worked
